<a href="https://colab.research.google.com/github/SarthakRaj1703/Machine-Learning-Self-Projects/blob/main/Sonar_Mine_or_Rock_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing libraries

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split #can split data into training and testing data
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import accuracy_score #to tell us the accuracy of our data

Data Collection and Processing Steps

In [8]:
#to load the csv data to a pandas dataframe
sonar_data = pd.read_csv('/content/Copy of sonar data.csv',header = None)
sonar_data.head()

       0       1       2       3       4   ...      56      57      58      59  60
0  0.0200  0.0371  0.0428  0.0207  0.0954  ...  0.0180  0.0084  0.0090  0.0032   R
1  0.0453  0.0523  0.0843  0.0689  0.1183  ...  0.0140  0.0049  0.0052  0.0044   R
2  0.0262  0.0582  0.1099  0.1083  0.0974  ...  0.0316  0.0164  0.0095  0.0078   R
3  0.0100  0.0171  0.0623  0.0205  0.0205  ...  0.0050  0.0044  0.0040  0.0117   R
4  0.0762  0.0666  0.0481  0.0394  0.0590  ...  0.0072  0.0048  0.0107  0.0094   R

[5 rows x 61 columns]

In [11]:
sonar_data.describe()
sonar_data[60].value_counts()

M    111
R     97
Name: 60, dtype: int64

In [12]:
sonar_data.groupby(60).mean()

          0         1         2   ...        57        58        59
60                                ...
M   0.034989  0.045544  0.050720  ...  0.009060  0.008695  0.006930
R   0.022498  0.030303  0.035951  ...  0.006677  0.007078  0.006024

[2 rows x 60 columns]

Data Pre-processing

In [13]:
#separating data and labels
#X stores values, Y stores labels
X = sonar_data.drop(columns = 60, axis = 1)
Y = sonar_data[60]
print(X,Y)

         0       1       2       3   ...      56      57      58      59
0    0.0200  0.0371  0.0428  0.0207  ...  0.0180  0.0084  0.0090  0.0032
1    0.0453  0.0523  0.0843  0.0689  ...  0.0140  0.0049  0.0052  0.0044
2    0.0262  0.0582  0.1099  0.1083  ...  0.0316  0.0164  0.0095  0.0078
3    0.0100  0.0171  0.0623  0.0205  ...  0.0050  0.0044  0.0040  0.0117
4    0.0762  0.0666  0.0481  0.0394  ...  0.0072  0.0048  0.0107  0.0094
..      ...     ...     ...     ...  ...     ...     ...     ...     ...
203  0.0187  0.0346  0.0168  0.0177  ...  0.0065  0.0115  0.0193  0.0157
204  0.0323  0.0101  0.0298  0.0564  ...  0.0034  0.0032  0.0062  0.0067
205  0.0522  0.0437  0.0180  0.0292  ...  0.0140  0.0138  0.0077  0.0031
206  0.0303  0.0353  0.0490  0.0608  ...  0.0034  0.0079  0.0036  0.0048
207  0.0260  0.0363  0.0136  0.0272  ...  0.0040  0.0036  0.0061  0.0115

[208 rows x 60 columns] 0      R
1      R
2      R
3      R
4      R
      ..
203    M
204    M
205    M
206    M
207    M
Name: 60, Length: 208, dtype: object

Training and Testing Data

In [14]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.1, stratify = Y, random_state = 1)
# ---- DESCRIPTION ---- #
# X_train, X_test are the data split of X, and Y_train and Y_test are corresponding labels

# train_test_split syntax
# (X,Y) are the matrices upon which the operations are performed
# test_size determines the ratio of the data allocated for testing and training (here 10%)
# stratify classifies data on the basis of labels (R/M)
# random_state is like a seed for splitting data

print(X.shape, X_train.shape, X_test.shape)

(208, 60) (187, 60) (21, 60)

Logistic Regression based Model Training

In [15]:
model = LogisticRegression()

In [16]:
#training the logistic regression model with the training data
model.fit(X_train, Y_train)

LogisticRegression()

Model Evaluation

In [17]:
#accuracy of the training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [18]:
print(training_data_accuracy)

0.8342245989304813

In [20]:
#accuracy score on the test data (real test)
X_test_prediction = model.predict(X_test)
testing_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print(testing_data_accuracy)

0.7619047619047619

Predictive System

In [21]:
input_data =(0.0124,0.0433,0.0604,0.0449,0.0597,0.0355,0.0531,0.0343,0.1052,0.2120,0.1640,0.1901,0.3026,0.2019,0.0592,0.2390,0.3657,0.3809,0.5929,0.6299,0.5801,0.4574,0.4449,0.3691,0.6446,0.8940,0.8978,0.4980,0.3333,0.2350,0.1553,0.3666,0.4340,0.3082,0.3024,0.4109,0.5501,0.4129,0.5499,0.5018,0.3132,0.2802,0.2351,0.2298,0.1155,0.0724,0.0621,0.0318,0.0450,0.0167,0.0078,0.0083,0.0057,0.0174,0.0188,0.0054,0.0114,0.0196,0.0147,0.0062)

input_data_numpy = np.asarray(input_data)

#reshape the array
input_data_reshaped = input_data_numpy.reshape(1,-1)

prediction = model.predict(input_data_reshaped)
print(prediction)

['R']